package astrobwtv3

import (
	"fmt"
	"math/bits"
	"math/rand"
	"os"
	"strings"
	"testing"
)

// applySubOp implements the 16-symbol sub-instruction vocabulary each
// pos2-dependent op's 4-step transform decomposes into -- the same
// operations Dirtybird-C-Miner's AVX2 kernel (simd_wolf.h) vectorizes,
// reimplemented here as plain scalar Go so the decomposition can be derived
// and verified against DEROHE's own applyBranchOp before any assembly is
// written. Semantics, not the encoding: this package derives which op maps
// to which 4-symbol sequence itself (see TestGenerateSubOpSequences) rather
// than trusting Dirtybird's CodeLUT.
func applySubOp(sub byte, x, pos2byte byte) byte {
	switch sub {
	case 0:
		return x + x
	case 1:
		return x - (x ^ 97)
	case 2:
		return x * x
	case 3:
		return x ^ pos2byte
	case 4:
		return ^x
	case 5:
		return x & pos2byte
	case 6:
		return x << (x & 3)
	case 7:
		return x >> (x & 3)
	case 8:
		return bits.Reverse8(x)
	case 9:
		return x ^ byte(bits.OnesCount8(x))
	case 10:
		return bits.RotateLeft8(x, int(x&7))
	case 11:
		return bits.RotateLeft8(x, 1)
	case 12:
		return x ^ bits.RotateLeft8(x, 2)
	case 13:
		return bits.RotateLeft8(x, 3)
	case 14:
		return x ^ bits.RotateLeft8(x, 4)
	case 15:
		return bits.RotateLeft8(x, 5)
	}
	panic("bad sub-op")
}

func applySubOpSeq(seq [4]byte, x, pos2byte byte) byte {
	for _, s := range seq {
		x = applySubOp(s, x, pos2byte)
	}
	return x
}

// referenceTransform calls applyBranchOp on a span-1 buffer, isolating just
// the op's per-byte transform (same technique as TestGenerateOpLUT).
func referenceTransform(op, input, pos2byte byte) byte {
	var buf [256]byte
	buf[0] = input
	buf[1] = pos2byte
	applyBranchOp(op, 0, 1, buf[:], 0, 0, Cipher{})
	return buf[0]
}

// TestGenerateSubOpSequences derives, for every pos2-dependent op (every op
// with opClass == opClassScalar except 0/253/254/255, which have side
// effects or cross-iteration dependencies outside this per-byte-transform
// model entirely), which 4-symbol sequence over applySubOp's 16-symbol
// vocabulary reproduces applyBranchOp's transform. Brute forces all 16^4
// candidates, screens against a handful of random (input, pos2byte) samples
// (a wrong sequence matching by coincidence on 10 random points is
// astronomically unlikely), then verifies every surviving candidate
// exhaustively across all 256x256 (input, pos2byte) pairs before accepting
// -- the same exhaustiveness standard as TestGenerateOpLUT. Writes the
// result to branch_op_subops.go.
//
// Run with: GENERATE_BRANCH_SUBOPS=1 go test -run TestGenerateSubOpSequences -v
func TestGenerateSubOpSequences(t *testing.T) {
	if os.Getenv("GENERATE_BRANCH_SUBOPS") == "" {
		t.Skip("set GENERATE_BRANCH_SUBOPS=1 to regenerate branch_op_subops.go")
	}

	rnd := rand.New(rand.NewSource(1))
	type sample struct{ input, pos2byte byte }
	samples := make([]sample, 12)
	for i := range samples {
		samples[i] = sample{byte(rnd.Intn(256)), byte(rnd.Intn(256))}
	}

	excluded := map[int]bool{0: true, 253: true, 254: true, 255: true}

	seqs := make(map[int][4]byte)
	var undecomposable []int

	for op := 0; op < 256; op++ {
		if opClass[op] != opClassScalar || excluded[op] {
			continue
		}

		var found [][4]byte
		for a := 0; a < 16; a++ {
			for b := 0; b < 16; b++ {
				for c := 0; c < 16; c++ {
				colLoop:
					for d := 0; d < 16; d++ {
						seq := [4]byte{byte(a), byte(b), byte(c), byte(d)}
						for _, s := range samples {
							if applySubOpSeq(seq, s.input, s.pos2byte) != referenceTransform(byte(op), s.input, s.pos2byte) {
								continue colLoop
							}
						}
						found = append(found, seq)
					}
				}
			}
		}

		// Exhaustively verify every screened candidate; keep the first that
		// survives full verification.
		var verified [4]byte
		verifiedOK := false
		for _, cand := range found {
			ok := true
		verifyLoop:
			for pos2byte := 0; pos2byte < 256; pos2byte++ {
				for input := 0; input < 256; input++ {
					if applySubOpSeq(cand, byte(input), byte(pos2byte)) != referenceTransform(byte(op), byte(input), byte(pos2byte)) {
						ok = false
						break verifyLoop
					}
				}
			}
			if ok {
				verified = cand
				verifiedOK = true
				break
			}
		}

		if !verifiedOK {
			undecomposable = append(undecomposable, op)
			continue
		}
		seqs[op] = verified
	}

	if len(undecomposable) > 0 {
		t.Fatalf("ops with no 4-symbol decomposition found (must stay on applyBranchOp): %v", undecomposable)
	}

	var sb strings.Builder
	sb.WriteString("package astrobwtv3\n\n")
	sb.WriteString("// Generated by TestGenerateSubOpSequences (branch_op_subops_gen_test.go).\n")
	sb.WriteString("// Do not edit by hand.\n")
	sb.WriteString("//\n")
	sb.WriteString("// opSubSeq[op] is the 4-symbol applySubOp sequence (see\n")
	sb.WriteString("// branch_op_subops_gen_test.go) that reproduces applyBranchOp's per-byte\n")
	sb.WriteString("// transform for op, derived by brute-force search and verified exhaustively\n")
	sb.WriteString("// across all 256x256 (input, step_3[pos2]) pairs -- not ported from\n")
	sb.WriteString("// Dirtybird's CodeLUT. Only populated for ops with opClass == opClassScalar\n")
	sb.WriteString("// and not in {0, 253, 254, 255} (see the generator's exclusion list).\n")
	sb.WriteString("var opSubSeq = map[byte][4]byte{\n")
	for op := 0; op < 256; op++ {
		if seq, ok := seqs[op]; ok {
			sb.WriteString(fmt.Sprintf("\t%d: {%d, %d, %d, %d},\n", op, seq[0], seq[1], seq[2], seq[3]))
		}
	}
	sb.WriteString("}\n")

	if err := os.WriteFile("branch_op_subops.go", []byte(sb.String()), 0644); err != nil {
		t.Fatalf("writing branch_op_subops.go: %v", err)
	}
	t.Logf("derived sub-op sequences for %d ops", len(seqs))
}
