package astrobwtv3

import (
	"fmt"
	"os"
	"strings"
	"testing"
)

// TestGenerateOpLUT classifies each of the 256 branch-loop opcodes by
// exhaustively testing applyBranchOp against every (input byte, step_3[pos2]
// byte) pair -- 65536 evaluations per op, not a sample -- since a coincidental
// match at a few sample points wouldn't prove step_3[pos2]-independence.
// Writes the result to branch_op_lut.go. The classification is derived
// entirely from applyBranchOp (DEROHE's own reference switch, extracted
// verbatim in branch_op.go); nothing here is ported from any external source.
//
// Run with: GENERATE_BRANCH_LUT=1 go test -run TestGenerateOpLUT -v
//
// opClass/opClassScalar/opClassZero/opClassLUT are defined in the generated
// branch_op_lut.go (not here) since pow.go, a non-test file, needs to see
// them too.
func TestGenerateOpLUT(t *testing.T) {
	if os.Getenv("GENERATE_BRANCH_LUT") == "" {
		t.Skip("set GENERATE_BRANCH_LUT=1 to regenerate branch_op_lut.go")
	}

	var class [256]byte
	var lut [256][256]byte

	for op := 0; op < 256; op++ {
		var reference [256]byte
		independent := true
		allZero := true

		for pos2byte := 0; pos2byte < 256; pos2byte++ {
			for input := 0; input < 256; input++ {
				var buf [256]byte
				for k := range buf {
					buf[k] = byte(k) // deterministic filler, only buf[0]/buf[1] matter for span=1
				}
				buf[0] = byte(input)
				buf[1] = byte(pos2byte)

				applyBranchOp(byte(op), 0, 1, buf[:], 0, 0, Cipher{})
				out := buf[0]

				if pos2byte == 0 {
					reference[input] = out
				} else if out != reference[input] {
					independent = false
				}
				if out != 0 {
					allZero = false
				}
			}
		}

		switch {
		case op == 254 || op == 255:
			// These carry a mandatory RC4 re-key (see applyBranchOp's case
			// 254,255) that isn't part of the step_3 transform this scan
			// observes -- their transform alone tests as pos2-independent,
			// but a fast path bypassing applyBranchOp would silently skip
			// the re-key. Force scalar regardless of what the scan found.
			// (Caught by TestAstroBWTv3 failing after wiring the fast paths
			// in without this override -- the KAT gate is what it's for.)
			class[op] = opClassScalar
		case allZero:
			class[op] = opClassZero
		case independent:
			class[op] = opClassLUT
			lut[op] = reference
		default:
			class[op] = opClassScalar
		}
	}

	var sb strings.Builder
	sb.WriteString("package astrobwtv3\n\n")
	sb.WriteString("// Generated by TestGenerateOpLUT (branch_op_lut_gen_test.go). Do not edit by hand.\n")
	sb.WriteString("//\n")
	sb.WriteString("// opClass[op] classifies each of the 256 branch-loop opcodes by how\n")
	sb.WriteString("// applyBranchOp's step_3[i] output depends on its inputs, derived empirically\n")
	sb.WriteString("// by exhaustively testing every (input byte, step_3[pos2] byte) pair against\n")
	sb.WriteString("// applyBranchOp itself (DEROHE's own reference switch, extracted verbatim in\n")
	sb.WriteString("// branch_op.go) -- nothing here is ported from any external source.\n")
	sb.WriteString("//   opClassScalar: output depends on more than just the input byte (either\n")
	sb.WriteString("//     references step_3[pos2], or -- op 0 specifically -- has a\n")
	sb.WriteString("//     cross-iteration dependency via its pos1/pos2 swap, which this test\n")
	sb.WriteString("//     detects indirectly since that swap also makes the span=1 output\n")
	sb.WriteString("//     depend on step_3[pos2]). Falls back to applyBranchOp unchanged.\n")
	sb.WriteString("//   opClassZero: output is 0 for every possible input, unconditionally.\n")
	sb.WriteString("//   opClassLUT: output is a pure function of the input byte alone; opLUT[op]\n")
	sb.WriteString("//     is that mapping, safe to reuse across any position and call.\n")
	sb.WriteString("const (\n\topClassScalar = iota\n\topClassZero\n\topClassLUT\n)\n\n")

	sb.WriteString("var opClass = [256]byte{\n")
	for op := 0; op < 256; op++ {
		sb.WriteString(fmt.Sprintf("\t%d: %d,\n", op, class[op]))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("var opLUT = [256][256]byte{\n")
	for op := 0; op < 256; op++ {
		if class[op] != opClassLUT {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t%d: {\n", op))
		for row := 0; row < 16; row++ {
			sb.WriteString("\t\t")
			for col := 0; col < 16; col++ {
				sb.WriteString(fmt.Sprintf("%d, ", lut[op][row*16+col]))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n")

	if err := os.WriteFile("branch_op_lut.go", []byte(sb.String()), 0644); err != nil {
		t.Fatalf("writing branch_op_lut.go: %v", err)
	}

	var nScalar, nZero, nLUT int
	for op := 0; op < 256; op++ {
		switch class[op] {
		case opClassScalar:
			nScalar++
		case opClassZero:
			nZero++
		case opClassLUT:
			nLUT++
		}
	}
	t.Logf("classified 256 ops: scalar=%d zero=%d lut=%d", nScalar, nZero, nLUT)
}
